### ISSUE TITLE
Add link to this repo in footer

### ISSUE THREAD

**Issue by niclasleonbock** [niclasleonbock/hacktoberfest-status#18]
In the footer, a link to this repo should be added so it's easier for interested people to contribute.

I was thinking about something like this:
instead of 
```html
<p>This site is in no way affiliated with DigitalOcean, GitHub or the Hacktoberfest project.</p>
```
use 
```html
<p>This site is in no way affiliated with DigitalOcean, GitHub or the Hacktoberfest project. But it participates in the Hacktoberfest. So why not <a href="#">contribute on GitHub</a>?</p>
```
Of course you still need to replace the hashtag.

And please, feel free to use some different text or way of placing it :)

This adjustment must be made in both view files (index, status). I actually recommend you to split out a partial view and include it in both files.

**Comment by bezierer** [comment]
I can work on this :)

**Comment by niclasleonbock** [comment]
It's yours! Thank you for your contribution :)

**Comment by niclasleonbock** [comment]
Done with #19.
