### ISSUE TITLE
Add meta/og tags for status page

### ISSUE THREAD

**Issue by niclasleonbock** [niclasleonbock/hacktoberfest-status#23]
Now that we can share the status page we also need meta tags and og tags for the status page, at least when in sharing mode.

The description should be context-dependent (something like the sharing message, e.g. "$username completed 11 pull requests for Hacktoberfest!".

Also, the page title should be changed in sharing mode, e.g. to "Hacktoberfest stats of $username".

All the other fields can simply be copied over from the index page.

I'll let the decision open to you if you want to add some if-blocks to the view or rather copy it.

This relates to #7 and #6

**Comment by Tardog** [comment]
Hi! I’ve implemented the context-dependent status page, but before I submit a PR for this, I would like to take the time to add some tests for the status page in both sharing mode and "normal" mode.

**Comment by niclasleonbock** [comment]
Hi,
sure, take your time. Thanks for the notice :)

**Comment by Tardog** [comment]
Just a quick heads up: I will have time to finish this tomorrow.
