### ISSUE TITLE
do pull requests to my own projects count?

### ISSUE THREAD

**Issue by mrexodia** [niclasleonbock/hacktoberfest-status#27]
https://github.com/x64dbg/x64dbg/pull/1742 appears to be counted and I have write access to that repository...

**Comment by niclasleonbock** [comment]
Hi,
yes, pull requests to your own repositories do count (see [this tweet](https://twitter.com/digitalocean/status/782986259107028993) from last year).

Only the following requirements need to be met:
* The repository on which you open the pull request needs to be public
* Pull requests on your own repos also count
* Pull requests don't need to be accepted or merged to count
* The actual content of the pull requests doesn't matter

**Comment by mrexodia** [comment]
Alright, thanks!
