### ISSUE TITLE
Add favicons

### ISSUE THREAD

**Issue by niclasleonbock** [niclasleonbock/hacktoberfest-status#29]
We should add favicons so that the site can be easily identified in the tabs bar.

Please use this [site](https://realfavicongenerator.net/) to have favicons in all required sizes for each and every browser and device.

**Comment by christophereyes** [comment]
I claim this issue.

**Comment by RickBakkr** [comment]
Is @christophereyes still onto this or can I take over :-)

**Comment by niclasleonbock** [comment]
That's a good question. I'd say you can take over if he doesn't answer within the next few hours.

**Comment by RickBakkr** [comment]
I think 10 hours is enough. Will do this one soon :-)

**Comment by RickBakkr** [comment]
Done.

**Comment by niclasleonbock** [comment]
Resolved and closed with #33.
