### ISSUE TITLE
Add Open Graph tags

### ISSUE THREAD

**Issue by niclasleonbock** [niclasleonbock/hacktoberfest-status#6]
To make sharing more beautiful (and to improve SEO), [Open Graph](http://ogp.me/) tags should be added. Next to the Open Graph tags, normal meta tags would be nice to have as well.

Tags that are at least required:
- **meta keywords:** hacktoberfest, status, checker, tracker (I don't know what else)
- **meta description:** feel free to get creative or simply reuse "This little tool helps you to track your Hacktoberfest status." :)
- **og:description:** same as meta description
- **og:title:** Hacktoberfest Status Tracker
- **og:image:** you may use the hacktoberfest logo for this, but please note that svg is not supported and you will need to first convert it

If you want to add any other tags, feel free to do so!

As only the index view is publicly facing, you will only need to edit the file `resources/views/index.blade.php`.

Please note: I recommend you to open a separate branch.

**Comment by niclasleonbock** [comment]
We could also use one of the official "wallpapers":
https://nyc3.digitaloceanspaces.com/hacktoberfest/Hacktoberfest17-TWFB-02.png
https://nyc3.digitaloceanspaces.com/hacktoberfest/Hacktoberfest17-TWFB-03.png

https://hacktoberfest.digitalocean.com/eventkit

**Comment by bearzk** [comment]
can I give it a try on this one? :)
