### ISSUE TITLE
Add possibility to share the status

### ISSUE THREAD

**Issue by niclasleonbock** [niclasleonbock/hacktoberfest-status#7]
It would be really cool to be able to share the status. Services that I'm currently thinking of are twitter and facebook. I don't really have a detailed plan on how this could look like.

One possible way is to simply add two "share" buttons that pre-fill the message field of the service with all the relevant information.

The 'cooler' way would be to have an extra page for this which is then publicly accessible. Basically we could use the normal status page, but access it via a custom route.

**Comment by bearzk** [comment]
can I give it a try on this one? :)

**Comment by niclasleonbock** [comment]
Yes, you absolutely can.

I thought I already answered - but seems like I didn't, so please excuse the delay.

**Comment by niclasleonbock** [comment]
Hey @bearzk,
do you have any update on this? Are you still working on it or should I open it up for grabs again?

Thank you so far!

**Comment by bearzk** [comment]
hey!

Sorry I didn't find time in last days for it, but today I will send the PR!



Am 09.10.2017 um 21:41 schrieb Niclas Leon Bock <notifications@github.com<mailto:notifications@github.com>>:


Hey @bearzk<https://github.com/bearzk>,
do you have any update on this? Are you still working on it or should I open it up for grabs again?

Thank you so far!

-

**Comment by niclasleonbock** [comment]
Hey,

don't worry - I was just curious. I'm looking forward to receiving your PR :)
